---
- set_fact:
    lxc_backing_store: 'zfs'
  when: not(
          (zfs_root is undefined)
          or
          (zfs_root == 'none')
          or
          (zfs_root | trim == '')
        )

- name: Create LXC container
  lxc_container:
    name: "{{ container_name }}"
    template: debian
    template_options: --release stretch
    backing_store: "{{ lxc_backing_store | default('dir') }}"
    zfs_root: "{{ zfs_root }}"
    state: stopped
  register: container_info

- name: Deploy container configuration from template
  template:
    src: container.conf.j2
    dest: "{{ lxc_root }}/{{ container_name }}/config"
  notify: restart container

- meta: flush_handlers

- name: Print container info
  debug:
    var: container_info
    verbosity: 4

- name: Wait for the network to be setup in the containers
  when: container_info|changed
  pause: seconds=5

- name: Setup the container SSH
  lxc_container:
    name: "{{ container_name }}"
    container_command: apt-get update && apt-get install -y python-minimal openssh-server iputils-ping

- name: Create .ssh folder on container /root/
  file:
    dest: "{{ lxc_root }}/{{ container_name }}/rootfs/root/.ssh/"
    state: directory
    mode: 0700

- name: Set up authorized key from local ansible user on container
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    path: "{{ lxc_root }}/{{ container_name }}/rootfs/root/.ssh/authorized_keys"
    state: present
