---
- set_fact:
    lxc_backing_store: 'zfs'
  when: not(
          (zfs_root is undefined)
          or
          (zfs_root == 'none')
          or
          (zfs_root | trim == '')
        )

- name: Deploy container configuration from template
  template:
    src: container.conf.j2
    dest: "/etc/lxc/{{ location }}.conf"
  run_once: true

- name: Create LXC container
  lxc_container:
    name: "{{ container_name }}"
    config: "/etc/lxc/{{ location }}.conf"
    template: download
    template_options: "--dist {{ lxc_distribution }} --release {{ lxc_release }} --arch {{ lxc_arch }}"
    backing_store: "{{ lxc_backing_store | default('dir') }}"
    zfs_root: "{{ zfs_root }}"
  register: container_info

- name: Add bind mounts
  blockinfile:
    path: "/{{ zfs_root }}/{{ container_name }}/config"
    marker: "# {mark} ANSIBLE bind_mounts"
    block: |
      {% if bind_mounts is defined %}
      {% for mount in bind_mounts %}
      lxc.mount.entry = {{ mount.src }} {{ mount.dest | regex_replace('^\/') }} none bind,optional,create.dir{% if mount.opts is defined %},{{ mount.opts }} {% endif %}

      {% endfor %}
      {% endif %}
  when: bind_mounts is defined

- name: Wait for network to come up
  wait_for_connection:
    delay: 1
    timeout: 30

- name: Print container info
  debug:
    var: container_info
    verbosity: 2

- name: Setup the container SSH
  lxc_container:
    name: "{{ container_name }}"
    container_command: apt-get update && apt-get install -y python-minimal openssh-server iputils-ping

- name: Create .ssh folder on container /root/
  file:
    dest: "{{ lxc_root }}/{{ container_name }}/rootfs/root/.ssh/"
    state: directory
    mode: 0700

- name: Set up authorized key from local ansible user on container
  authorized_key:
    user: root
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    path: "{{ lxc_root }}/{{ container_name }}/rootfs/root/.ssh/authorized_keys"
    state: present

- name: Remove old keys from known_hosts
  known_hosts:
    name: "{{ item.name }}"
    state: absent
  loop: "{{ container_info.lxc_container }}"

- name: Add new keys to known_hosts
  known_hosts:
    name: "{{ item.0.name }}"
    key: "{{ lookup('pipe', 'ssh-keyscan {{ item.1 }}') }}"
  loop: "{{ lookup('subelements', container_info.lxc_container, 'ips', {'skip_missing': True}) }}"
