---
- name: Set LXC backing store to ZFS
  set_fact:
    lxc_backing_store: 'zfs'
  when: zfs_root is defined

- name: Deploy container configuration from template
  template:
    src: container.conf.j2
    dest: "/etc/lxc/{{ location }}.conf"
  run_once: true

- name: Create LXC container
  lxc_container:
    name: "{{ container_name }}"
    config: "/etc/lxc/{{ location }}.conf"
    template: download
    template_options: "--dist {{ lxc_distribution }} --release {{ lxc_release }} --arch {{ lxc_arch }}"
    backing_store: "{{ lxc_backing_store | default('dir') }}"
    zfs_root: "{{ zfs_root | default(omit) }}"
  register: container_info
  notify: prepare new container

- name: Add bind mounts
  blockinfile:
    path: "/{{ zfs_root }}/{{ container_name }}/config"
    marker: "# {mark} ANSIBLE bind_mounts"
    block: |
      {% if bind_mounts is defined %}
      {% for mount in bind_mounts %}
      lxc.mount.entry = {{ mount.src }} {{ mount.dest | regex_replace('^\/') }} none bind,optional,create.dir{% if mount.opts is defined %},{{ mount.opts }} {% endif %}

      {% endfor %}
      {% endif %}
  when: bind_mounts is defined
  notify: restart container

- name: Print container info
  debug:
    var: container_info
    verbosity: 2
