---
- name: Restart LXC container
  lxc_container:
    name: "{{ container_name }}"
    state: restarted
  listen: restart container

- name: Wait for network to come up
  wait_for_connection:
    delay: 1
    timeout: 60
  listen: restart container
